### ISSUE TITLE
Problem since last update

### ISSUE THREAD

**Issue by devleaks** [Insolita/yii2-iconpicker#2]
Hello,
I have numerous problem with your picker since you updated it lately.
First, widget attributes likes rows, columns, etc. have been removed and need to be passed to clientOptions instead. So at least the doc needs updating.

I could only get your widget to work in simple forms like this:

`'icon'=>['type'=> Form::INPUT_WIDGET,
                     'widgetClass' => Iconpicker::className(),
                     'clientOptions' => [
                        'iconset'=> 'fontawesome',
                        'rows' => 6,
                        'columns' => 8,
                     ]
            ],
`
I cannot get it to work properly inside Kartik's DetailView update form:
`[
                'attribute' => 'icon',
                'value' => Icon::show(str_replace('fa-', '', $model->icon)),
                'format' => 'raw',
                'type'=> DetailView::INPUT_WIDGET,
                'widgetOptions' => [
                    'class' => Iconpicker::className(),
                    'clientOptions' => [
                        'iconset'=> 'fontawesome',
                    ]
                ],
            ],
`

I revert to 1.0 until you have a look. Thanks.

**Comment by Insolita** [comment]
Yes, new version has breaking compatibilty, I specially increase major version and doc was updated in release day. What wrong with doc?
You can use early version with composer settings 

> "insolita/yii2-iconpicker": "~1.0"

i don't use Kartik's DetailView and can't  check compatibility quick, but please describe what happens when you use it with DetailView form? Php error, javascript error, no error, but not work ?
